name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run deployment script on remote server
        env:
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER 'bash -s' << 'EOF'
          #!/bin/bash

          # Configuration
          APP_DIR="/var/www/spark-server"
          GITHUB_REPO="https://github.com/SparkEdUAB/sparked-next.git"
          BRANCH="main"
          PM2_APP_NAME="sparked-app"

          # Ensure we're in the correct directory
          cd $APP_DIR || exit

          # Pull the latest changes from the specified branch
          echo "Pulling latest changes from $BRANCH branch..."
          git pull origin $BRANCH

          # Install dependencies
          echo "Installing dependencies..."
          yarn

          # Build the Next.js app
          echo "Building the Next.js app..."
          yarn run build

          # Restart the PM2 process (assuming you're using PM2 to manage the Node.js process)
          echo "Restarting the app..."
          pm2 restart $PM2_APP_NAME

          # Check if the app is running
          if pm2 show $PM2_APP_NAME > /dev/null 2>&1; then
              echo "Deployment successful! The app is now running."
          else
              echo "Deployment failed. The app is not running."
              exit 1
          fi

          echo "Deployment process completed."
          EOF
