name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run deployment script on remote server
        env:
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER 'bash -s' << 'EOF'
          #!/bin/bash

          # Configuration
          SCRIPT_PATH="$HOME/deploy.sh"

          # Ensure the deploy.sh script is executable
          chmod +x $SCRIPT_PATH

          # Run the deploy.sh script
          $SCRIPT_PATH
          EOF
